FROM eclipse-temurin:17-jdk-jammy

# Ensure latest CA certs
RUN apt-get update && apt-get install -y ca-certificates ca-certificates-java && update-ca-certificates


# Step 2: Set a directory for the app
WORKDIR /app

# Step 3: Copy the JAR file
COPY target/marketprocessor-0.0.1-SNAPSHOT.jar app.jar

# Step 4: Run the app
ENTRYPOINT ["java","-jar","/app/app.jar"]


